import nodemailer from 'nodemailer';

export async function sendIncidentNotification(log: {
  id: string;
  vector: string;
  coordinates: string;
  severity: string;
  notes: string;
  timestamp: string;
}) {
  const host = process.env.SMTP_HOST || 'smtp.ethereal.email';
  const port = parseInt(process.env.SMTP_PORT || '587');
  const secure = process.env.SMTP_SECURE === 'true'; // true for 465, false for other ports
  const user = process.env.SMTP_USER;
  const pass = process.env.SMTP_PASS;

  let transporter;

  if (user && pass) {
    // Production SMTP
    transporter = nodemailer.createTransport({
      host,
      port,
      secure,
      auth: { user, pass }
    });
  } else {
    // Generate transient test SMTP service on ethereal.email
    try {
      const testAccount = await nodemailer.createTestAccount();
      transporter = nodemailer.createTransport({
        host: 'smtp.ethereal.email',
        port: 587,
        secure: false,
        auth: {
          user: testAccount.user,
          pass: testAccount.pass
        }
      });
    } catch (err) {
      console.error('Failed to create Nodemailer test account, falling back to mock logger:', err);
      // Dummy logger fallback if network blocks test account creation
      return {
        success: true,
        mocked: true,
        info: 'Logs printed to console since no SMTP configured.'
      };
    }
  }

  const fromAddress = process.env.SMTP_FROM || (user ? `"Aquacare Alerts" <${user}>` : '"Aquacare Alerts" <alerts@aquacare-telemetry.com>');

  const mailOptions = {
    from: fromAddress,
    to: 'tanmayagarwal2201@gmail.com',
    subject: `⚠️ Incident Alert: [${log.severity.toUpperCase()}] ${log.vector} Initiated`,
    html: `
      <div style="font-family: sans-serif; padding: 20px; color: #333; max-width: 600px; border: 1px solid #e5e7eb; border-radius: 8px;">
        <h2 style="color: #b71511; margin-top: 0;">⚠️ New Incident Telemetry Initiated</h2>
        <p>A new water quality incident has been reported in the Aquacare system and requires review.</p>
        
        <table style="width: 100%; border-collapse: collapse; margin-top: 15px; margin-bottom: 20px;">
          <tr style="background-color: #f9fafb;">
            <th style="padding: 10px; border: 1px solid #e5e7eb; text-align: left; font-weight: bold; width: 140px;">Field</th>
            <th style="padding: 10px; border: 1px solid #e5e7eb; text-align: left;">Value</th>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e5e7eb; font-weight: bold;">Log ID</td>
            <td style="padding: 10px; border: 1px solid #e5e7eb; font-family: monospace; font-size: 13px;">${log.id}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e5e7eb; font-weight: bold;">Vector</td>
            <td style="padding: 10px; border: 1px solid #e5e7eb;">${log.vector}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e5e7eb; font-weight: bold;">Severity</td>
            <td style="padding: 10px; border: 1px solid #e5e7eb;">
              <span style="display: inline-block; padding: 4px 10px; font-size: 11px; font-weight: bold; border-radius: 4px; text-transform: uppercase;
                ${log.severity === 'CRITICAL' ? 'background-color: #fee2e2; color: #991b1b; border: 1px solid #fca5a5;' : 
                  log.severity === 'ELEVATED' ? 'background-color: #fef9c3; color: #854d0e; border: 1px solid #fde047;' : 
                  'background-color: #dcfce7; color: #166534; border: 1px solid #86efac;'}">
                ${log.severity}
              </span>
            </td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e5e7eb; font-weight: bold;">Coordinates</td>
            <td style="padding: 10px; border: 1px solid #e5e7eb; font-size: 13px;">${log.coordinates}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e5e7eb; font-weight: bold;">Timestamp</td>
            <td style="padding: 10px; border: 1px solid #e5e7eb; font-size: 13px;">${new Date(log.timestamp).toLocaleString()}</td>
          </tr>
          <tr>
            <td style="padding: 10px; border: 1px solid #e5e7eb; font-weight: bold;">Field Notes</td>
            <td style="padding: 10px; border: 1px solid #e5e7eb; font-size: 13px; font-style: italic; white-space: pre-wrap;">${log.notes}</td>
          </tr>
        </table>
        
        <hr style="border: 0; border-top: 1px solid #e5e7eb;" />
        <p style="font-size: 11px; color: #6b7280; text-align: center; margin-bottom: 0;">
          This is an automated alert generated by the Aquacare Prevention Hub. Please do not reply directly to this email.
        </p>
      </div>
    `
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Incident alert email sent successfully:', info.messageId);
    
    let previewUrl = null;
    if (!user || !pass) {
      previewUrl = nodemailer.getTestMessageUrl(info);
      console.log('Ethereal Mail Preview URL (for testing):', previewUrl);
    }
    
    return { success: true, messageId: info.messageId, previewUrl };
  } catch (error) {
    console.error('Error sending incident alert email:', error);
    return { success: false, error };
  }
}
